### ISSUE TITLE
Needs a license

### ISSUE THREAD

**Issue by colinrymer** [spartansystems/cimple_hosted_forms#1]

**Comment by colinrymer** [comment]
We should probably discuss as a company what license we want to use. I'm a big fan of the MIT license from past work.

**Comment by squaresurf** [comment]
:+1: for MIT although the [Apache License 2.0](https://tldrlegal.com/license/apache-license-2.0-%28apache-2.0%29) does protect against patent trolls. In the end I prefer the ubiquity and simplicity of the MIT license.

**Comment by handerson** [comment]
I've added a license: b4d1484e6dc4032ce793bcf937ba087c06f6ac24
